# Generated by Django 6.0.7 on 2026-07-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ['project', 'role', 'user']},
        ),
    ]
