# Generated by Django 6.0.7 on 2026-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('REVIEW_CREATED', 'Review Created'), ('REVIEW_UPDATED', 'Review Updated'), ('REVIEW_DELETED', 'Review Deleted')], max_length=30),
        ),
    ]
