# Generated by Django 6.0.7 on 2026-07-30 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_projectmember_options'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('CPP', 'C++'), ('C', 'C'), ('JAVA', 'Java'), ('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('TYPESCRIPT', 'TypeScript'), ('GO', 'Go'), ('RUST', 'Rust')], max_length=20)),
                ('code', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='snippets', to='tags.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='snippets_sn_project_2dbe68_idx'), models.Index(fields=['author'], name='snippets_sn_author__70302c_idx'), models.Index(fields=['language'], name='snippets_sn_languag_8c1caa_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'title'), name='unique_snippet_title_per_project')],
            },
        ),
    ]
