# Generated by Django 6.0.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snippets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('code', models.TextField()),
                ('message', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippet_versions', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='snippets.snippet')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['snippet'], name='versions_sn_snippet_29d4d0_idx'), models.Index(fields=['version_number'], name='versions_sn_version_5d5cc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('snippet', 'version_number'), name='unique_version_per_snippet')],
            },
        ),
    ]
