# Generated by Django 6.0.7 on 2026-08-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='snippetversion',
            new_name='versions_sn_snippet_a4a81e_idx',
            old_name='versions_sn_snippet_29d4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='snippetversion',
            new_name='versions_sn_version_6b1064_idx',
            old_name='versions_sn_version_5d5cc0_idx',
        ),
    ]