# Generated by Django 6.0.7 on 2026-07-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=30)),
                ('comment', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task'], name='reviews_rev_task_id_a5ef3c_idx'), models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx'), models.Index(fields=['status'], name='reviews_rev_status_5966f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'reviewer'), name='unique_review_per_user_per_task')],
            },
        ),
    ]
